//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jcoleman_Lunch.RestaurantService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://localhost/RestaurantService", ConfigurationName="RestaurantService.RestaurantService")]
    public interface RestaurantService {
        
        // CODEGEN: Parameter 'order' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="order")]
        jcoleman_Lunch.RestaurantService.getOrdersResponse getOrders(jcoleman_Lunch.RestaurantService.getOrders request);
        
        // CODEGEN: Parameter 'menu' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="menu")]
        jcoleman_Lunch.RestaurantService.getMenusResponse getMenus(jcoleman_Lunch.RestaurantService.getMenus request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/RestaurantService")]
    public partial class order : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string orderNameField;
        
        private double priceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string orderName {
            get {
                return this.orderNameField;
            }
            set {
                this.orderNameField = value;
                this.RaisePropertyChanged("orderName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("price");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18054")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://localhost/RestaurantService")]
    public partial class menu : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string menuNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string menuName {
            get {
                return this.menuNameField;
            }
            set {
                this.menuNameField = value;
                this.RaisePropertyChanged("menuName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOrders", WrapperNamespace="http://localhost/RestaurantService", IsWrapped=true)]
    public partial class getOrders {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/RestaurantService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string menuName;
        
        public getOrders() {
        }
        
        public getOrders(string menuName) {
            this.menuName = menuName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOrdersResponse", WrapperNamespace="http://localhost/RestaurantService", IsWrapped=true)]
    public partial class getOrdersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/RestaurantService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("order", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public jcoleman_Lunch.RestaurantService.order[] order;
        
        public getOrdersResponse() {
        }
        
        public getOrdersResponse(jcoleman_Lunch.RestaurantService.order[] order) {
            this.order = order;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMenus", WrapperNamespace="http://localhost/RestaurantService", IsWrapped=true)]
    public partial class getMenus {
        
        public getMenus() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getMenusResponse", WrapperNamespace="http://localhost/RestaurantService", IsWrapped=true)]
    public partial class getMenusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://localhost/RestaurantService", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("menu", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public jcoleman_Lunch.RestaurantService.menu[] menu;
        
        public getMenusResponse() {
        }
        
        public getMenusResponse(jcoleman_Lunch.RestaurantService.menu[] menu) {
            this.menu = menu;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RestaurantServiceChannel : jcoleman_Lunch.RestaurantService.RestaurantService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RestaurantServiceClient : System.ServiceModel.ClientBase<jcoleman_Lunch.RestaurantService.RestaurantService>, jcoleman_Lunch.RestaurantService.RestaurantService {
        
        public RestaurantServiceClient() {
        }
        
        public RestaurantServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RestaurantServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestaurantServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestaurantServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        jcoleman_Lunch.RestaurantService.getOrdersResponse jcoleman_Lunch.RestaurantService.RestaurantService.getOrders(jcoleman_Lunch.RestaurantService.getOrders request) {
            return base.Channel.getOrders(request);
        }
        
        public jcoleman_Lunch.RestaurantService.order[] getOrders(string menuName) {
            jcoleman_Lunch.RestaurantService.getOrders inValue = new jcoleman_Lunch.RestaurantService.getOrders();
            inValue.menuName = menuName;
            jcoleman_Lunch.RestaurantService.getOrdersResponse retVal = ((jcoleman_Lunch.RestaurantService.RestaurantService)(this)).getOrders(inValue);
            return retVal.order;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        jcoleman_Lunch.RestaurantService.getMenusResponse jcoleman_Lunch.RestaurantService.RestaurantService.getMenus(jcoleman_Lunch.RestaurantService.getMenus request) {
            return base.Channel.getMenus(request);
        }
        
        public jcoleman_Lunch.RestaurantService.menu[] getMenus() {
            jcoleman_Lunch.RestaurantService.getMenus inValue = new jcoleman_Lunch.RestaurantService.getMenus();
            jcoleman_Lunch.RestaurantService.getMenusResponse retVal = ((jcoleman_Lunch.RestaurantService.RestaurantService)(this)).getMenus(inValue);
            return retVal.menu;
        }
    }
}
