package JaxbClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.6
 * 2013-08-09T23:53:57.984-06:00
 * Generated source version: 2.7.6
 * 
 */
@WebService(targetNamespace = "http://localhost/RestaurantService", name = "RestaurantService")
@XmlSeeAlso({ObjectFactory.class})
public interface RestaurantService {

    @WebResult(name = "order", targetNamespace = "")
    @RequestWrapper(localName = "getOrders", targetNamespace = "http://localhost/RestaurantService", className = "JaxbClient.GetOrders")
    @WebMethod
    @ResponseWrapper(localName = "getOrdersResponse", targetNamespace = "http://localhost/RestaurantService", className = "JaxbClient.GetOrdersResponse")
    public java.util.List<JaxbClient.Order> getOrders(
        @WebParam(name = "menuName", targetNamespace = "")
        java.lang.String menuName
    );

    @WebResult(name = "menu", targetNamespace = "")
    @RequestWrapper(localName = "getMenus", targetNamespace = "http://localhost/RestaurantService", className = "JaxbClient.GetMenus")
    @WebMethod
    @ResponseWrapper(localName = "getMenusResponse", targetNamespace = "http://localhost/RestaurantService", className = "JaxbClient.GetMenusResponse")
    public java.util.List<JaxbClient.Menu> getMenus();
}
